# Placeholders: <new-line> | <timer>

BOOLEANS:
  # Maintenance Boolean
  # For activate and deactivate
  # the maintenance option.
  MAINTENANCE: true

  # MOTDs Booleans
  # For activate and deactivate
  # the motds options.
  MOTD: true
  MOTD-SERVER-PING: true

  # Players Booleans
  # For activate and deactivate
  # the players options.
  MAX-PLAYERS: true
  JUST-ONE-MORE: false
  FAKE-PLAYERS: false

MOTDS:
  - '&6&lExample Network <new-line>&7This is the default description! Change it on &e&nconfig.yml'
  - "&3&lExample Network <new-line>&7This is the default description! Change it on &b&nconfig.yml"

# This option only work with
# § symbol and not with & symbol.
MOTD-SERVER-PING:
  - "§7§m---*----------------------*---"
  - "             §6§lExample Network  "
  - ""
  - "§7This is the default message!"
  - "§7Change it on §e§nconfig.yml"
  - ""
  - "§a* Store: §fstore.example.com"
  - "§d* Website: §fwww.example.com"
  - "§9* Discord: §fdiscord.example.com"
  - "§b* Twitter: §f@Example"
  - "§7§m---*----------------------*---"

MAINTENANCE:
  MAINTENANCE-KICK: "&cThe network is currently undergoing maintenance, check back soon!"
  MAINTENANCE-SERVER-PING: "Maintenance"

  MAINTENANCE-ON: "&aThe maintenance mode has been enabled successfully!"
  MAINTENANCE-OFF: "&CThe maintenance mode has been disabled successfully!"

PLAYERS:
  MAX-PLAYERS: 1000

FAKE-PLAYERS:
  AMOUNT: 5

HUB:
  HUB-SERVER: "hub"
  SEND-HUB: "&bSending you to the hub!"
  ALREADY-CONNECTED: "&cYou are already connected to the hub!"

MESSAGES:
  CONFIG-RELOADED: "&aThe config has been reloaded successfully!"

