# Variables: <new-line> | <timer>
BOOLEANS:
  MAINTENANCE: true
  MOTD: true
  MOTD-SERVER-PING: true

MOTDS:
  - '&6&lExample Network <new-line>&7This is the default description! Change it on &e&nconfig.yml'

# This option only work with
# § symbol and not with & symbol.
MOTD-SERVER-PING:
  - "§7§m---*----------------------*---"
  - "             §6§lExample Network  "
  - ""
  - "§7This is the default message!"
  - "§7Change it on §e§nconfig.yml"
  - ""
  - "§a* Store: §fstore.example.com"
  - "§d* Website: §fwww.example.com"
  - "§9* Discord: §fdiscord.example.com"
  - "§b* Twitter: §f@Example"
  - "§7§m---*----------------------*---"

MAINTENANCE:
  MAINTENANCE-KICK: "&cThe network is currently undergoing maintenance, check back soon!"
  MAINTENANCE-SERVER-PING: "Maintenance"

  MAINTENANCE-ON: "&aThe maintenance mode has been enabled successfully!"
  MAINTENANCE-OFF: "&CThe maintenance mode has been disabled successfully!"

HUB:
  SEND-HUB: "&bSending you to the hub!"
  ALREADY-CONNECTED: "&cYou are already connected to the hub!"

MESSAGES:
  CONFIG-RELOADED: "&aThe config has been reloaded successfully!"

